language: node_js
node_js:
  - "6.9.0"
branches:
  only:
    - master
script:
  - echo "Deploing!"
  - ls -l
  - npm install
  - cd angular4-shop
  - ng build --prod
install:
  - npm install -g firebase-tools
  - npm install -g angular-cli
after_success:
  - firebase deploy --token $FIREBASE_TOKEN