language: node_js
node_js:
  - "6.11.0"
branches:
  only:
    - master
script:
  - echo "Deploing!"
  - npm install
  - npm run build:prod
install:
  - npm install -g firebase-tools
  - npm install -g angular-cli
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
